# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gavin Sonne
email: gavin.j.sonne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neuroslice.github.io/" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: Slicehawk
github_username:  neuroslice
#facebook_username: neuroslice
instagram_username: slicehawk
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/gsonne/

# Address information
#address_street: --
address_city: Salinas
address_state: CA
address_zip: 93901

# Build settings
markdown: kramdown
